.TH lcmc "1" "2011-10-01" "lcmc 1.0.2" "User Commands"

.SH NAME
lcmc \- a cluster GUI

.SH SYNOPSIS
.B lcmc

.SH DESCRIPTION

LCMC is a Java GUI that configures, manages and visualizes Linux clusters
in a way that is not possible to be web-based. Specificaly it manages
clusters that use one or more of these components: Pacemaker, Corosync,
Heartbeat, DRBD, KVM, XEN and LVM.

.SH AUTHOR
Written by Rasto Levrinc.

.SH "REPORTING BUGS"
Report bugs to <rasto.levrinc@gmail.com>.

.SH COPYRIGHT
LCMC Copyright 2011 Rasto Levrinc.
DRBD MC Copyright 2007 - 2011 LINBIT HA-Solutions GmbH

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

.SH "SEE ALSO"
http://lcmc.sourceforge.net
